Vagrant.configure('2') do |config|

  config.vm.synced_folder "~/.dotfiles", "/home/vagrant/.dotfiles"

  config.vm.provision "shell", inline: <<-SCRIPT
    set -e

    echo Becoming vagrant user...
    export HOME=/home/vagrant
    cd $HOME
    su vagrant -

    echo Installing preferred shell...
    sudo apt-get install fish -y > /dev/null 2>&1
    chsh vagrant -s /usr/bin/fish

    echo Installing dotfile manager...
    sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm -y > /dev/null 2>&1
    sudo apt-get update -y > /dev/null 2>&1
    sudo apt-get install rcm -y > /dev/null 2>&1

    echo Linking dotfiles...
    rcup > /dev/null 2>&1
    chown $USER.$USER -R $HOME

  SCRIPT

end
