Vagrant.configure('2') do |config|

  config.vm.synced_folder "~/.dotfiles", "/home/vagrant/.dotfiles"

  config.vm.provision "shell", inline: <<-SCRIPT
    set -e

    echo Becoming vagrant user...
    export USER=vagrant
    su $USER -
    export GROUP=vagrant
    export HOME=/home/$USER

    # Setting up config directory...
    export XDG_CONFIG_HOME=${XDG_CONFIG_HOME-$HOME/.config}
    export CONFIG_DIR=$XDG_CONFIG_HOME

    # Updating installer...
    sudo apt-get -y update > /dev/null 2>&1

    echo Installing preferred shell...
    sudo add-apt-repository -y ppa:fish-shell/release-3
    sudo apt-get -y update > /dev/null 2>&1
    sudo apt-get -y install fish > /dev/null 2>&1
    chsh vagrant -s /usr/bin/fish

    echo Installing dotfile manager...
    wget -qO - https://apt.thoughtbot.com/thoughtbot.gpg.key | sudo apt-key add - > /dev/null 2>&1
    echo "deb https://apt.thoughtbot.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list  > /dev/null 2>&1
    sudo apt-get -y update > /dev/null 2>&1
    sudo apt-get -y install rcm > /dev/null 2>&1

    echo Linking dotfiles...
    rcup > /dev/null 2>&1

    echo Installing version manager...
    git clone https://github.com/asdf-vm/asdf.git $CONFIG_DIR/asdf --branch v0.7.8 > /dev/null 2>&1
    sudo apt-get -y install build-essential > /dev/null 2>&1
    sudo apt-get -y install unzip > /dev/null 2>&1

    echo Owning home...
    sudo chown -R $USER:$GROUP $HOME

  SCRIPT

end
