###
# APPLICATIONS
##

tap caskroom/cask

install brew-cask

# DEPENDENCIES
cask install xquartz virtualbox

# PRODUCTIVITY
cask install alfred daisydisk menumeters onepassword
# cask install sparrow

# DEVELOPMENT
cask install dropbox iterm2 sourcetree vagrant

# OTHER
cask install colorpicker-hex ffmpegx flux mactex steam utorrent vlc


####
# LIBRARIES
##

tap thoughtbot/formulae

# CONFIGURATION MANAGEMENT
install rcm

# LANGUAGES
install erlang exenv nvm rbenv ruby-build

# DATA STORES
install memcached postgresql protobuf rabbitmq redis
install ossp-uuid

# NETWORKING
install nginx openssl

# TEXT AND DOCUMENT UTILITIES
install pandoc

# CODE UTILITIES
install cloc git gource hub

# VIZUALIZATION UTILITIES
install cairo imagemagick
install graphviz --with-bindings --with-freetype --with-librsvg --with-pangocairo

# COMMANDLINE UTILITIES
install readline tree

# OTHER
install cowsay fortune pianobar


####
# COMPLETIONS
##

tap homebrew/completions

# RUBY
install ruby-completion gem-completion bundler-completion
install rake-completion rails-completion

# OTHER
install vagrant-completion


####
# FINISHERS
##

# Trigger alfred completion
cask alfred link

# GC downloads
cask cleanup
cleanup
