####
# Build Dependencies
##
brew "coreutils"
brew "cmake"
brew "gcc"
brew "gettext"
brew "icu4c" # for postgres
brew "libsodium"
brew "ossp-uuid" # for postgres
brew "ncurses"
brew "openblas"
brew "openssl@1.1"
brew "pkgconf" # for nerves, postgres
brew "readline"
brew "uconv" # for postgres
brew "wxwidgets"
brew "xz" # for burrito, nerves
brew "zlib"
brew "zstd" # for bakeware
# Scenic
brew "glfw"
brew "glew"
# Nerves
brew "fwup"
brew "squashfs"

####
# CLI tools
##
brew "ack"
brew "bash"
brew "bat"
brew "brotli"
brew "cloc"
brew "curl"
brew "entr"
brew "ffmpeg"
brew "fish"
brew "git"
brew "graphviz"
brew "htop"
brew "mise"
brew "pandoc"
brew "rcm"
brew "sloc"
brew "tree"
brew "watch"

####
# Apps
##
# brew "discord"

####
# Fonts
##
brew "font-fira-code"
brew "font-monaspace"
